services:
  - type: web
    name: reqmap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: Flask run
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    preInstallCommand:
      apt-get update && apt-get install -y graphviz graphviz-dev